### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by a-lazy-cat** [PunishXIV/Saucy#11]
Today I reinstalled my computer system(from win11 download to win10), so I need to reinstall the plugin again. But this time I installed it failed.  It told me “The installation of the plug-in saucy failed. Please restart the game and try again. If a bug exists, please contact the plugin author.” I have used unbanplugin, and I have tired restart the game several times, but I still couldn't install it. 

I can install Artisan, autohook successfully but I can't install Marketbuddy, either, These are all third plugins 

By the way, I played the Chinese version. Could you please give me some help or suggestions?

**Comment by Taurenkey** [comment]
Punish doesn't officially support CN versions, you will have to source another fork for this.

**Comment by a-lazy-cat** [comment]
Does Punish will support CN version in the future? Like after CN ffxiv update some versions?

**Comment by Cyame** [comment]
> Does Punish will support CN version in the future? Like after CN ffxiv update some versions?

Just simply install the corresponding version of saucy using the local dev plugins, it works good for me:)
