### ISSUE TITLE
Dalamud Crash w/ Multiple Clients

### ISSUE THREAD

**Issue by SonyUSA** [PunishXIV/Saucy#13]
Running 2 clients (1 doing TT and 1 doing CaC) will eventually cause the CaC (secondary) client to crash Dalamud with the following error. However, the client continues to play CaC properly until you select on option on the dialogue. Additionally, would it be possible to split the stats to a per-character SQL DB? This may solve the issue and also allow users to track individual character farming rates.

---------------------------
Dalamud
---------------------------
An internal error in a Dalamud plugin occurred.
The game must close.

SQLiteException
SQLite-net, SQLite.SQLiteConnection::Update

Plugin that caused this:
Saucy

Click "Yes" and remove it.

More information has been recorded separately.

Do you want to disable all plugins the next time you start the game?
---------------------------
Yes   No   
---------------------------

**Comment by Taurenkey** [comment]
Saucy doesn’t use SQL, it’s just writing to a json file to track stats.

I’m not really interested in per character stats at the moment, or supporting multi-client play as I do neither of those.
