### ISSUE TITLE
New ezMiniCactpot breaks Saucy integration/automation

### ISSUE THREAD

**Issue by shinji257** [PunishXIV/Saucy#24]
It seems that since ezMiniCactpot changed the highlight color the automation has broke.  I did check to make sure it is enabled and that it does detect the plugin is there but does nothing once the card comes up.  Nothing appears in `xllog` when I check there.

![image](https://github.com/user-attachments/assets/748ea44d-a61d-4b6a-8142-e445e47d8295)

**Comment by Taurenkey** [comment]
This is now fixed
