### ISSUE TITLE
Add Randomization

### ISSUE THREAD

**Issue by ripsnortntear** [PunishXIV/Saucy#26]
Observations from EW to DT

I've noticed a couple of areas where we can enhance the gameplay experience:

Dynamic Difficulty Settings for "Out on a Limb": The difficulty settings are now dynamic, instead of static. It would be nice if we could introduce a Random setting that chooses a difficulty level at random for each play. This would make the gameplay feel more natural and unpredictable.

Randomizing Spot Selection on "Out on a Limb": Currently, the game searches for spots in a predictable sequence (25, 50, 75, etc.). To add a bit of human-like unpredictability, we could randomize the selection of the starting spot. For example, the game could randomly choose one of the three spots (25, 50, or 75) as the starting point, and then proceed to search the remaining spots in a random order.

This would make the gameplay feel more organic and less formulaic.

**Comment by Limiana** [comment]
That would add too much unnecessary complication to the code.
In addition when as a human you farm something, you aim to always execute the most optimal way possible. Like when you're killing a boss, you're always executing the same rotation. If you are experienced enough, you wouldn't randomly miss a skill in your opener.

**Comment by Taurenkey** [comment]
To add to what Lim said, there's zero reason to do this other than to make it more inefficient. Nobody knows if you're playing perfectly or like dog shit. So unless you're doing something silly like livestreaming 12 hours of Out on a Limb attempts, there's no reason for us to randomize anything here.
