### ISSUE TITLE
[Feature Request] Out on a Limb

### ISSUE THREAD

**Issue by yjywybb** [PunishXIV/Saucy#3]
A related script has been written before and can be found at https://github.com/CynanC/FF14-Tools-Package/blob/master/cutting.py

**Comment by Taurenkey** [comment]
That's great except it's useless to us as it is. We write in C# and there's issues with using key presses to do things.

**Comment by yjywybb** [comment]
If it can be keyed in the same way as Cuff A Cur, then you might be able to refer to the way how the script works.

All in all, I look forward to the inclusion of the Out on a Limb feature!

**Comment by Taurenkey** [comment]
The script is wholly incompatible with how we work in Dalamud plugins. It relies too much on screen reading for me to use it. I would be better doing my own implementation and right now I don't have the necessary information to make it consistent enough to work in Saucy.

**Comment by ripsnortntear** [comment]
this can be closed
