### ISSUE TITLE
How can I add it? 

### ISSUE THREAD

**Issue by a-lazy-cat** [PunishXIV/Saucy#8]
I put the Saucy.json path (https://github.com/PunishXIV/Saucy/blob/master/Saucy/Saucy.json) to my Dalamud but I can't find it in my lib. Did I do something wrong?

**Comment by kawaii** [comment]
You need to add the repo, not the link to the project's own json file.

`https://love.puni.sh/ment.json`

**Comment by a-lazy-cat** [comment]
I used your link but I still couldn't find the mod, so I installed it manually. But it is not compatible with my Dalamud. Is there a solution?

**Comment by kawaii** [comment]
Are you using the CN version of Dalamud?

**Comment by a-lazy-cat** [comment]
Yes!

**Comment by a-lazy-cat** [comment]
Can‘t’ the CN version of Dalamud use it? Is there any solution?

**Comment by a-lazy-cat** [comment]
Thank you for answering me! I have successfully run it! Does the mod also work for Out on a Limb Machine?
